---
- name: install dnsmasq
  yum: pkg=dnsmasq state=installed

- name: configure dnsmasq
  template: src=dnsmasq.conf
            dest=/etc/dnsmasq.conf
            owner=root group=root mode=0644
  notify: restart dnsmasq

- name: start and enable dnsmasq
  service: name=dnsmasq state=started enabled=true

